packaging_format = 2

id = "baserow"
name = "Baserow"
description.en = "No-code open source database & application builder"
description.fr = "Application open source de création d’applications et de bases de données sans code"

version = "2.3.2~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "MIT"
website = "https://baserow.io/"
admindoc = "https://baserow.io/docs/index"
code = "https://github.com/baserow/baserow"

[integration]
yunohost = ">= 12.1.6"
architectures = "all"
helpers_version = "2.1"
multi_instance = false
ldap = false
sso = false

disk = "2000M"
ram.build = "5000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
 
[resources]    
    [resources.sources.main]

    url = "https://github.com/baserow/baserow/archive/refs/tags/2.3.2.tar.gz" 
    sha256 = "8ad9deff016be6e3eebeed47b22861d36122a2ffaba943985846805bb3d84869"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
	allow_email = true

    [resources.install_dir]   
   
    [resources.permissions]
    main.url = "/"
	main.auth_header = false
    [resources.ports.backend]

    [resources.ports.frontend]
    [resources.apt]
    packages = "postgresql redis-server python3-venv python3-pip libpq-dev"

    [resources.data_dir]
    subdirs = ["media"]
    group = "www-data:rx"

    [resources.database]
    type = "postgresql"
	
	[resources.apt.extras.mise]
	repo = "deb https://mise.jdx.dev/deb stable main"
	key = "https://mise.jdx.dev/gpg-key.pub"
	packages = [
		"mise"
	]
	
    [resources.nodejs]
    version = "24"
    
