#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
  ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-backend" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-frontend" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-celey" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-celery-export" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

domain=$new_domain
path=$new_path
ynh_config_change_url_nginx


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-backend" --action="start"
ynh_systemctl --service="$app-frontend" --action="start"
ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-celery-export" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
