#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================
ynh_script_progression "Generating $app's secrets..."

session_secret=$(ynh_string_random --length=24)


#=================================================
# CREATE A PostgreSQL DATABASE
#=================================================
ynh_script_progression "Configuring a PostgreSQL database..."

ynh_psql_db_shell <<< "ALTER ROLE baserow SET client_encoding TO 'utf8';"
ynh_psql_db_shell <<< "ALTER ROLE baserow SET default_transaction_isolation TO 'read committed';"
ynh_psql_db_shell <<< "ALTER ROLE baserow SET timezone TO 'UTC';"
ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON DATABASE baserow TO baserow;"
ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON SCHEMA public TO baserow;"
ynh_psql_db_shell <<< "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO baserow;"


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/$app"

#=================================================
# APP ENV CONFIGURATION
#=================================================
ynh_config_add --template=".frontend.env" --destination="$install_dir/$app/.env"
ynh_config_add --template=".backend.env" --destination="$install_dir/$app/web-frontend.env"


#=================================================
# BUILDING BACKEND
#=================================================
ynh_script_progression "Building Backend..."

pushd "$install_dir"
  python3 -m venv venv
  source venv/bin/activate
  pip3 install -e ./baserow/backend
  pip3 install -e ./baserow/premium/backend
  pip3 install -e ./baserow/enterprise/backend
  pip install -r baserow/backend/requirements/base.txt
  source .env
  baserow migrate
  baserow sync_templates
  deactivate
popd

#=================================================
# BUILDING FRONTEND
#=================================================

pushd "$install_dir/$app/web-frontend"
  yarn install
  echo N | ./node_modules/nuxt/bin/nuxt.js build --config-file config/nuxt.config.local.js
  npm install --legacy-peer-depsnpm 
  run build
popd







