#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================
ynh_script_progression "Generating $app's secrets..."

secret_key=$(ynh_string_random --length=24)


#=================================================
# CREATE A PostgreSQL DATABASE
#=================================================
ynh_script_progression "Configuring a PostgreSQL database..."

ynh_psql_db_shell <<< "ALTER ROLE baserow SET client_encoding TO 'utf8';"
ynh_psql_db_shell <<< "ALTER ROLE baserow SET default_transaction_isolation TO 'read committed';"
ynh_psql_db_shell <<< "ALTER ROLE baserow SET timezone TO 'UTC';"
ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON DATABASE baserow TO baserow;"
ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON SCHEMA public TO baserow;"
ynh_psql_db_shell <<< "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO baserow;"


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/$app"

#=================================================
# ADMIN USER CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

admin_mail=$(ynh_user_get_info --username=$admin --key="mail")
ynh_hide_warnings npm install bcryptjs
admin_pw_hash=$(node -e "console.log(require('bcryptjs').hashSync('"$admin_pw"', 10));")

#=================================================
# APP ENV CONFIGURATION
#=================================================
ynh_config_add --template=".backend.env" --destination="$install_dir/$app.env"
ynh_config_add --template=".frontend.env" --destination="$install_dir/$app/web-frontend/.env"


#=================================================
# BUILDING BACKEND
#=================================================
ynh_script_progression "Building $app's backend..."

pushd "$install_dir/$app"
  python3 -m venv venv
  source venv/bin/activate
  pip3 install -e ./backend
  pip3 install -e ./premium/backend
  pip3 install -e ./enterprise/backend
  pip install -r backend/requirements/base.txt
  set -a  
  source .env
  set +a
  export DJANGO_SETTINGS_MODULE='baserow.config.settings.base'
  export
  baserow migrate
  baserow sync_templates
  deactivate
popd

#=================================================
# BUILDING FRONTEND
#=================================================
ynh_script_progression "Building $app's frontend..."

pushd "$install_dir/$app/web-frontend"
  yarn install

  CI=true ./node_modules/nuxt/bin/nuxt.js build --config-file config/nuxt.config.local.js --quiet
  npm install --legacy-peer-deps
  npm run build
popd

#=================================================
# AUTHENTICATION
#=================================================
ynh_script_progression "Configuring $app's authentication

ynh_psql_db_shell  <<< "INSERT INTO public.auth_user (email, password, username) VALUES ('"$admin_mail"', '"$admin_pw_hash"', '"$admin_mail"');"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_app_setting_set --app=$app --key=secret_key --value=$secret_key

ynh_config_add_systemd

ynh_config_add_logrotate

touch /var/log/$app/$app.log
chown -R $app:www-data /var/log/$app/
yunohost service add "$app" --description="Saltcorn No-Code Editor" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"

