#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================
ynh_script_progression "Generating $app's secrets..."

secret_key=$(ynh_string_random --length=24)
jwt_secret=$(ynh_string_random --length=24)
upload_max_size=100

email_smtp_host=$(cat /etc/yunohost/current_host)
email_smtp_port=587
email_smtp_use_ssl=false
email_smtp_use_tls=true
email_smtp_user="$app"
email_smtp_password="$mail_pwd"
from_email="$app@$domain"

#=================================================
# CREATE A PostgreSQL DATABASE
#=================================================
ynh_script_progression "Configuring a PostgreSQL database..."

ynh_psql_db_shell <<< "ALTER ROLE baserow SET client_encoding TO 'utf8';"
ynh_psql_db_shell <<< "ALTER ROLE baserow SET default_transaction_isolation TO 'read committed';"
ynh_psql_db_shell <<< "ALTER ROLE baserow SET timezone TO 'UTC';"
ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON DATABASE baserow TO baserow;"
ynh_psql_db_shell <<< "GRANT ALL PRIVILEGES ON SCHEMA public TO baserow;"
ynh_psql_db_shell <<< "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO baserow;"


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/$app"


#=================================================
# APP ENV CONFIGURATION
#=================================================
ynh_config_add --template="backend.env" --destination="$install_dir/$app/.env"
ynh_config_add --template="frontend.env" --destination="$install_dir/$app/web-frontend/.env"


#=================================================
# BUILDING BACKEND
#=================================================
ynh_script_progression "Building $app's backend..."

pushd "$install_dir/$app"

  python3 -m venv venv
  source venv/bin/activate
    set -a  
    source .env
    set +a
  if [ $full_version == 1 ]; then  
    ynh_script_progression "Installing Premium and Enterprise dependencies..."
    ynh_hide_warnings pip install -e ./backend
    ynh_hide_warnings pip install -e ./premium/backend
    ynh_hide_warnings pip install -e ./enterprise/backend
  else
    ynh_script_progression "Installing Base dependencies..."
    export BASEROW_OSS_ONLY=true
    ynh_replace --match='#BASEROW_OSS_ONLY=true[^"]*' --replace="BASEROW_OSS_ONLY=true" --file="${install_dir}/${app}/.env"
    ynh_hide_warnings pip install -e ./backend
  fi
  
  ynh_hide_warnings pip install -r backend/requirements/base.txt
  
  if [ $full_version == 1 ]; then
  ynh_script_progression "Migrating $app's database (Premium and Enterprise version)... "
  baserow migrate >/dev/null
  ynh_script_progression "Syncing... Have a break of 30 minutes !"
  ynh_hide_warnings baserow sync_templates
  else
  ynh_script_progression "Migrating $app's database (Base version)... "
  baserow migrate >/dev/null
  fi
  deactivate
popd

#=================================================
# BUILDING FRONTEND
#=================================================
ynh_script_progression "Building $app's frontend..."

pushd "$install_dir/$app/web-frontend"
ynh_script_progression "Yarn install..."
corepack enable
corepack prepare  yarn@latest --activate
yarn install
ynh_script_progression "Build..."

  CI=true ./node_modules/nuxt/bin/nuxt.js build --config-file config/nuxt.config.local.js --quiet

ynh_script_progression "Npm install..."

  ynh_hide_warnings npm install --legacy-peer-deps
ynh_script_progression "Npm run build..."
 
  ynh_hide_warnings npm run build
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_app_setting_set --app=$app --key=secret_key --value=$secret_key
ynh_app_setting_set --app=$app --key=jwt_secret --value=$jwt_secret
#ynh_app_setting_set --app=$app --key=email_smtp --value=false
ynh_app_setting_set --app=$app --key=email_smtp_port --value=$email_smtp_port
ynh_app_setting_set --app=$app --key=email_smtp_use_ssl --value=$email_smtp_use_ssl
ynh_app_setting_set --app=$app --key=email_smtp_use_tls --value=$email_smtp_use_tls
ynh_app_setting_set --app=$app --key=email_smtp_user --value=$email_smtp_user
ynh_app_setting_set --app=$app --key=email_smtp_password --value=$email_smtp_password
ynh_app_setting_set --app=$app --key=from_email --value=$from_email

ynh_app_setting_set --app=$app --key=upload_max_size --value=$upload_max_size



ynh_config_add_systemd --service="$app-backend" --template="baserow-backend.service"
ynh_config_add_systemd --service="$app-frontend" --template="baserow-frontend.service"
ynh_config_add_systemd --service="$app-celery" --template="baserow-celery.service"
ynh_config_add_systemd --service="$app-celery-export" --template="baserow-celery-export.service"

ynh_config_add_logrotate

touch /var/log/$app/$app-backend.log
touch /var/log/$app/$app-frontend.log

chown -R $app:www-data /var/log/$app/
chown -R $app:www-data $data_dir

yunohost service add "$app-backend" --description="Baserow No-Code Editor - backend" --log="/var/log/$app/$app-backend.log"
yunohost service add "$app-frontend" --description="Baserow No-Code Editor - frontend" --log="/var/log/$app/$app-frontend.log"
yunohost service add "$app-celery" --description="Baserow No-Code Editor - Celery worker" --log="/var/log/$app/$app-celery.log"
yunohost service add "$app-celery-export" --description="Baserow No-Code Editor - Celery worker Export" --log="/var/log/$app/$app-celery-export.log"


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-backend" --action="start"
ynh_systemctl --service="$app-frontend" --action="start"
ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-celery-export" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"

