#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

version=$(ynh_app_upstream_version)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-backend" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-frontend" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-celery" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-celery-export" --action="stop" --log_path="systemd"

if ynh_hide_warnings yunohost service status "$app-backend" >/dev/null; then
    yunohost service remove "$app-backend"
fi
ynh_config_remove_systemd "$app-backend"

if ynh_hide_warnings yunohost service status "$app-frontend" >/dev/null; then
    yunohost service remove "$app-frontend"
fi
ynh_config_remove_systemd "$app-frontend"

if ynh_hide_warnings yunohost service status "$app-celery" >/dev/null; then
    yunohost service remove "$app-celery"
fi
ynh_config_remove_systemd "$app-celery"

if ynh_hide_warnings yunohost service status "$app-celery-export" >/dev/null; then
    yunohost service remove "$app-celery-export"
fi
ynh_config_remove_systemd "$app-celery-export"


if ynh_hide_warnings yunohost service status "$app-backend" >/dev/null; then
    yunohost service remove "$app-backend"
fi
ynh_config_remove_systemd "$app-backend"

if ynh_hide_warnings yunohost service status "$app-frontend" >/dev/null; then
    yunohost service remove "$app-frontend"
fi
ynh_config_remove_systemd "$app-frontend"

if ynh_hide_warnings yunohost service status "$app-celery" >/dev/null; then
    yunohost service remove "$app-celery"
fi
ynh_config_remove_systemd "$app-celery"

if ynh_hide_warnings yunohost service status "$app-celery-export" >/dev/null; then
    yunohost service remove "$app-celery-export"
fi
ynh_config_remove_systemd "$app-celery-export"



#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."
chown -R $app:$app "$install_dir"
# Download, check integrity, uncompress and patch the source from manifest.toml

# Had issues with this when upgrading to 2.0.1 : upgrade failed and complained about missing premium plugin even with OSE version !
#if [ -d "$install_dir/$app/venv" ]; then
#    mv "$install_dir/$app/venv" "/tmp/${app}_backup_venv"
#fi

mv "$install_dir/$app/.env" "/tmp/${app}.backup_env"
mv "$install_dir/$app/web-frontend/.env" "/tmp/${app}.web-frontend.backup_env"


ynh_setup_source --dest_dir="$install_dir/$app" --full_replace=1 --keep=.env web-frontend/.env


#if [ -d "/tmp/${app}_backup_venv" ]; then
#    mv "/tmp/${app}_backup_venv" "$install_dir/$app/venv"
#fi

mv "/tmp/${app}.backup_env" "$install_dir/$app/.env" 
mv "/tmp/${app}.web-frontend.backup_env" "$install_dir/$app/web-frontend/.env"

#=================================================
# CONFIG FILES
#=================================================
ynh_script_progression "Retrieving $app's configuration..."

jwt_secret=$(ynh_app_setting_get --app=$app --key=jwt_secret)
secret_key=$(ynh_app_setting_get --app=$app --key=secret_key)
upload_max_size=$(ynh_app_setting_get --app=$app --key=upload_max_size)
email_smtp_host=$(ynh_app_setting_get --app=$app --key=email_smtp_host)
email_smtp_port=$(ynh_app_setting_get --app=$app --key=email_smtp_port)
email_smtp_use_ssl=$(ynh_app_setting_get --app=$app --key=email_smtp_use_ssl)
email_smtp_use_tls=$(ynh_app_setting_get --app=$app --key=email_smtp_use_tls)
email_smtp_user=$(ynh_app_setting_get --app=$app --key=email_smtp_user)
email_smtp_password=$(ynh_app_setting_get --app=$app --key=email_smtp_password)
from_email=$(ynh_app_setting_get --app=$app --key=from_email)

#=================================================
# BUILDING BACKEND
#=================================================
ynh_script_progression "Building $app's backend..."

pushd "$install_dir/$app"
  # python3 -m venv venv
  if [ ! -d "venv" ]; then
      python3 -m venv venv
  fi

  source venv/bin/activate
    set -a  
    source .env
    set +a
    ynh_script_progression "Installing dependencies..."
    ynh_hide_warnings pip install -e ./backend
  ynh_hide_warnings pip install  --upgrade --no-cache-dir -r backend/requirements/base.txt
  ynh_script_progression "Migrating $app's database... "
  baserow migrate >/dev/null
  deactivate
popd

#=================================================
# BUILDING FRONTEND
#=================================================
ynh_script_progression "Building $app's frontend..."

chown -R $app:$app "$install_dir"

pushd "$install_dir/$app/web-frontend"
  ynh_hide_warnings ynh_exec_as_app corepack enable
  ynh_hide_warnings ynh_exec_as_app corepack prepare  yarn@latest --activate
  ynh_hide_warnings ynh_exec_as_app ynh_exec_as_app yarn install --frozen-lockfile --non-interactive
  ynh_hide_warnings ynh_exec_as_app ynh_exec_as_app CI=true ./node_modules/nuxt/bin/nuxt.js build --config-file config/nuxt.config.local.js --quiet
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_app_setting_set --app=$app --key=secret_key --value=$secret_key

ynh_config_add_systemd --service="$app-backend" --template="baserow-backend.service"
ynh_config_add_systemd --service="$app-frontend" --template="baserow-frontend.service"
ynh_config_add_systemd --service="$app-celery" --template="baserow-celery.service"
ynh_config_add_systemd --service="$app-celery-export" --template="baserow-celery-export.service"

yunohost service add $app-backend --description="Baserow No-Code Editor - backend" --log=/var/log/$app/$app-backend.log
yunohost service add $app-frontend --description="Baserow No-Code Editor - frontend" --log=/var/log/$app/$app-frontend.log
yunohost service add $app-celery --description="Baserow No-Code Editor - Celery worker" --log=/var/log/$app/$app-celery.log
yunohost service add $app-celery-export --description="Baserow No-Code Editor - Celery worker Export" --log=/var/log/$app/$app-celery-export.log

ynh_config_add_logrotate

touch /var/log/$app/$app-backend.log
touch /var/log/$app/$app-frontend.log

chown -R $app:www-data /var/log/$app/

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-backend" --action="start"
ynh_systemctl --service="$app-frontend" --action="start"
ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-celery-export" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"



